# Generated by Django 5.0.6 on 2024-06-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default='ESZ'),
        ),
    ]
