# Generated by Django 5.0.6 on 2024-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer_created_at'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='offers', to='reviews.review'),
        ),
    ]
