services:
    app:
        image: qwizii/dealhub:latest
        container_name: dealhub_app_prod
        command: gunicorn dealhub.wsgi:application --bind 0.0.0.0:8000
        expose:
            - "8000"
        volumes:
            - static_volume:/app/staticfiles/
        environment:
            - DEBUG=${DEBUG}
            - SECRET_KEY=${SECRET_KEY}
            - DB_ENGINE=${DB_ENGINE}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - PEXELS_API_KEY=${PEXELS_API_KEY}
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - dealhub-network
        tty: true
        healthcheck:
            test: [ "CMD-SHELL", "curl --fail http://localhost:8000 || exit 1" ]
            interval: 30s
            timeout: 30s
            retries: 3
    db:
        image: postgres:15.1
        container_name: dealhub_db_prod
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        restart: unless-stopped
        expose:
            - 5435
        networks:
            - dealhub-network
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 30s
            timeout: 30s
            retries: 3
    nginx:
        image: nginx:stable-alpine3.17-slim
        container_name: dealhub_nginx_prod
        ports:
            - 8000:80
        volumes:
            - static_volume:/app/staticfiles/
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - dealhub-network
    coolify-helper:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dealhub_coolify_helper
        environment:
            - DEBUG=${DEBUG}
            - SECRET_KEY=${SECRET_KEY}
            - DB_ENGINE=${DB_ENGINE}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - PEXELS_API_KEY=${PEXELS_API_KEY}
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - dealhub-network

networks:
    dealhub-network:

volumes:
    static_volume:
    pgdata: