# Generated by Django 5.0.6 on 2024-05-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_groups_alter_account_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
